# Generated by Django 4.0 on 2021-12-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication_app', '0005_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_label', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('publication', models.ManyToManyField(blank=True, to='publication_app.Post')),
            ],
        ),
    ]
