# Generated by Django 4.0 on 2021-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0005_alter_post_author'),
        ('hashtag_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='publication',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='publication_app.Post'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
