# Generated by Django 4.0 on 2021-12-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0003_rename_hashtag_label_hashtag_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='publication',
            new_name='posts',
        ),
    ]
