# Generated by Django 4.0 on 2021-12-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0004_rename_publication_hashtag_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='label',
            new_name='hashtag_label',
        ),
    ]
