# Generated by Django 4.0 on 2021-12-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
