# Generated by Django 4.0 on 2021-12-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='media',
        ),
    ]
