# Generated by Django 4.0 on 2021-12-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0009_rename_image_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
    ]
