# Generated by Django 4.0 on 2021-12-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('publication_app', '0010_remove_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='media_app.media'),
        ),
    ]
