# Generated by Django 4.0 on 2022-01-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hashtag_app', '0005_rename_label_hashtag_hashtag_label'),
        ('follower_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('follow_hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='hashtag_app.hashtag')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_hashtags', to='auth.user')),
            ],
            options={
                'ordering': ['-create_date'],
                'unique_together': {('follower', 'follow_hashtag')},
            },
        ),
    ]
