# Generated by Django 4.0 on 2021-12-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0012_remove_post_media_post_file'),
        ('comments_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('like_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments_app.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publication_app.post'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post'), ('user', 'comment')},
        ),
    ]
