# Generated by Django 4.0 on 2021-12-09 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Неверный телефонный номер', regex='^\\+?\\d{8,15}$')])),
                ('bio', models.TextField(blank=True, null=True)),
                ('github', models.URLField(blank=True, max_length=2048, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='auth.user')),
            ],
        ),
    ]
